# Generated by Django 6.0.5 on 2026-05-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_casestudy_experience_navitem_project_siteprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='whatsapp_url',
            field=models.CharField(blank=True, help_text='Full wa.me URL, e.g. https://wa.me/254798934667', max_length=300),
        ),
    ]
