# Generated by Django 6.0.5 on 2026-05-17 11:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0003_blogpostpage_author_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='content',
            field=wagtail.fields.StreamField([('rich_text', 0), ('code', 5), ('image', 8), ('quote', 9), ('callout', 12)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote'], 'label': 'Rich text'}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Plain text'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('json', 'JSON'), ('sql', 'SQL')]}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 220, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('filename', 1), ('language', 2), ('code', 3), ('caption', 4)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 160, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 6), ('alt_text', 7), ('caption', 4)]], {}), 9: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Quote'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('note', 'Note'), ('tip', 'Tip'), ('warning', 'Warning')]}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'blockquote']}), 12: ('wagtail.blocks.StructBlock', [[('style', 10), ('heading', 1), ('text', 11)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Legacy article body. Use the content blocks below for new posts.'),
        ),
    ]
