# Generated by Django 6.0.5 on 2026-05-17 11:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0004_blogpostpage_content_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, help_text='Legacy article body. Use the content blocks below for new posts.', verbose_name='Legacy body'),
        ),
    ]
