# Generated by Django 6.0.5 on 2026-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0005_alter_blogpostpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Exclude this page from search engine indexes.'),
        ),
    ]
