# Generated by Django 6.0.5 on 2026-05-28 13:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcms', '0008_blogpostpage_new_stream_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField()),
                ('ip_source', models.CharField(blank=True, max_length=40)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=1000)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('country_code', models.CharField(blank=True, max_length=8)),
                ('country_name', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_unique_cookie', models.BooleanField(default=False)),
                ('is_likely_bot', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='blogcms.blogpostpage')),
            ],
            options={
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['visited_at'], name='blogvisit_visited_at_idx'), models.Index(fields=['post', 'visited_at'], name='blogvisit_post_time_idx'), models.Index(fields=['ip_address'], name='blogvisit_ip_idx'), models.Index(fields=['country_code'], name='blogvisit_country_idx')],
            },
        ),
    ]
